<a href="https://colab.research.google.com/github/devadarshjeevankumar/devadarshjeevankumar/blob/main/Copy_of_Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Three powerful packages
- Numpy
- Pandas
- Matplotlib

## Numpy

- Used for scientific computing
- Helps to create/ manage N-dimensional array

In [ ]:
import numpy as np #importing numpy package+

In [ ]:
x = np.array([1,2,3,4]) #creating numpy array from list

In [ ]:
print(x)

[1 2 3 4]


In [ ]:
print(type(x))  

<class 'numpy.ndarray'>


In [ ]:
print(x.shape) #printing the dimension of the array

(4,)


In [ ]:
y = np.array([[1,2],[3,4]])

In [ ]:
print(y)
print(y.shape)

[[1 2]
 [3 4]]
(2, 2)


In [ ]:
z = np.array([[1+0j,2+5j]])  #printing the dimension of the numpy array

In [ ]:
print(z)
print(type(z))

[[1.+0.j 2.+5.j]]
<class 'numpy.ndarray'>


In [ ]:
a = np.zeros((2,3)) #creating numpy array of zeros , of dimension (2,3)

In [ ]:
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(a.shape)

(2, 3)


In [ ]:
b = np.ones((2,3))  #creating numpy array of ones , of dimension (2,3) and integer type)

In [ ]:
print(b)

[[1 1 1]
 [1 1 1]]


In [ ]:
d = np.eye(3) ## identity matrix

In [ ]:
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
e = np.arange(10) ##similar to Range function

In [ ]:
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
e = np.arange(12, 21)

In [ ]:
print(e)

[12 13 14 15 16 17 18 19 20]


In [ ]:
e = np.arange(5,20,3)

In [ ]:
print(e)

[ 5  8 11 14 17]


In [ ]:
f = np.linspace(1,20,6) ## It create intervals

In [ ]:
print(f)

[ 1.          4.16666667  7.33333333 10.5        13.66666667 16.83333333
 20.        ]


In [ ]:
g = np.random.random((3,4)) #returns an array of specified shape and fills it with random floats in the half-open interval [0.0, 1.0).

In [ ]:
print(g)

[[0.06361828 0.46314684 0.25385488 0.83515093]
 [0.47213821 0.87316298 0.41874094 0.80978929]
 [0.81529581 0.34524176 0.37004918 0.79510533]]


In [ ]:
h = np.random.random((3,4)) #creating a numpy array having dimension (3,4) with random elements

In [ ]:
print(h.reshape(4,3)) 

[[0.93139117 0.07990736 0.59575067]
 [0.96704847 0.0082584  0.41994651]
 [0.35723369 0.5446182  0.05671504]
 [0.60034791 0.40851153 0.59700139]]


In [ ]:
x = np.arange(12)
print(x)
print(x[7])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
7


In [ ]:
print(x[-1])

11


In [ ]:
x.resize(3,4)

In [ ]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(x[-1,-1])

11


In [ ]:
print(x[2][3])

11


In [ ]:
y = np.arange(1,26)
print(y)
print(y[:6])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[1 2 3 4 5 6]


In [ ]:
print(y[10:])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [ ]:
print(y[10:15])

[11 12 13 14 15]


In [ ]:
print(y[-5:])

[21 22 23 24 25]


In [ ]:
print(y[3:-3])

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


In [ ]:
print(y[::3])

[ 1  4  7 10 13 16 19 22 25]


In [ ]:
print(y.reshape((5,5)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
y = y.reshape((5,5))
print(y)
print(y[:5,:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
print(y[2:-1,1:-1])

[[12 13 14]
 [17 18 19]]


In [ ]:
print(y[:,:-1])

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]


In [ ]:
print(y[:,-1])

[ 5 10 15 20 25]


In [ ]:
print(y[::,::2])

[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]


In [ ]:
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
print(y[1::2,1::2])

[[ 7  9]
 [17 19]]


In [ ]:
a = np.arange(1,6)
b = np.arange(6,11)
print(a+b)
print(a-b)
print(b-a)
print(a**2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[5 5 5 5 5]
[ 1  4  9 16 25]


In [ ]:
print(a>3)

[False False False  True  True]


In [ ]:
a = np.arange(0,4).reshape((2,2))

In [ ]:
b = np.eye(2)

In [ ]:
print(a*b) ##Wrong

[[0. 0.]
 [0. 3.]]


In [ ]:
print(np.dot(a,b)) ##Matrix multiplication

[[0. 1.]
 [2. 3.]]


In [ ]:
x = np.arange(1,10).reshape(3,3)

In [ ]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(x.sum())

45


In [ ]:
print(x.sum(axis=0))#column sum

[12 15 18]


In [ ]:
print(x.sum(axis=1))# row sum

[ 6 15 24]


In [ ]:
x = np.arange(1,19).reshape(3,2,3)   # Three dimensional Matrix

In [ ]:
print(x.sum(axis=1))

[[ 5  7  9]
 [17 19 21]
 [29 31 33]]


In [ ]:
print(x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [ ]:
x = np.arange(1,10).reshape(3,3)

In [ ]:
print(x)
print(x.max())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


In [ ]:
print(x.sum())

45


In [ ]:
print(x.max(axis=0))

[7 8 9]


In [ ]:
print(x.transpose())


[[1 4 7]
 [2 5 8]
 [3 6 9]]
